resolver: lts-19.33
packages:
  - .

extra-deps:
- hashable-1.3.0.0
- rest-rewrite-0.3.0
- git: https://github.com/ucsd-progsys/liquidhaskell.git
  commit: b8780ee8d73d123adb39675ef87a2883f8aa1ecd
  subdirs:
    - .
    - liquid-base
    - liquid-containers
    - liquid-ghc-prim
    - liquid-prelude
- git: https://github.com/ucsd-progsys/liquid-fixpoint.git
  commit: 11a773a08e66cea13d8ddbf203ca32bd5cea97b2

allow-newer: true
