resolver: lts-18.18
packages:
  - .
extra-deps:
  - text-format-0.3.2
  - Diff-0.3.4
  - rest-rewrite-0.1.1
  - location:
    git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 599b0d3bc785bea95ef55dda110c71d635f4683d
  - location: 
    git: https://github.com/liquidhaskell/liquid-base
    commit: 79e2bee57ef6e34e69a80cd361bc8edde80da34a 
  - liquid-prelude-0.8.10.2 
  - location: 
    git: https://github.com/liquidhaskell/liquid-containers
    commit: 845942a8fdca5ab785c2e0e5202e5beaf94bc327
  - liquid-ghc-prim-0.6.1
  - location: 
    git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 33b0dec432b4cc3f911fac77e6819f1e35b0d6cc
#  - ../../liquidtypes/liquidhaskell
#  - ../../liquidtypes/liquidhaskell/liquid-base
#  - ../../liquidtypes/liquidhaskell/liquid-containers
#  - ../../liquidtypes/liquidhaskell/liquid-prelude
#  - ../../liquidtypes/liquidhaskell/liquid-ghc-prim
#  - ../../liquidtypes/liquidhaskell/liquid-fixpoint

allow-newer: true